"""Added new fields to the training

Revision ID: 18cc13347b55
Revises: 545a4f2b2e3e
Create Date: 2016-10-21 15:41:15.694876

"""

# revision identifiers, used by Alembic.
revision = '18cc13347b55'
down_revision = '545a4f2b2e3e'

from alembic import op
import sqlalchemy as sa


INSERTS = """"""
DELETES = """"""


def iter_statements(stmts):
    for st in [x for x in stmts.split('\n') if x]:
        op.execute(st)


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trainings', sa.Column('date', sa.Date(), nullable=True))
    op.add_column('trainings', sa.Column('description', sa.String(), nullable=False))
    op.add_column('trainings', sa.Column('distance', sa.Integer(), nullable=True))
    op.add_column('trainings', sa.Column('duration', sa.Interval(), nullable=True))
    op.add_column('trainings', sa.Column('elevation', sa.Integer(), nullable=True))
    op.add_column('trainings', sa.Column('heartrate', sa.Integer(), nullable=True))
    op.add_column('trainings', sa.Column('rating', sa.Integer(), nullable=True))
    op.add_column('trainings', sa.Column('sport', sa.Integer(), nullable=True))
    op.add_column('trainings', sa.Column('title', sa.String(), nullable=False))
    op.create_foreign_key('fk_trainings_uid_users', 'trainings', 'users', ['uid'], ['id'], use_alter=True)
    op.create_foreign_key('fk_trainings_gid_usergroups', 'trainings', 'usergroups', ['gid'], ['id'], use_alter=True)
    ### end Alembic commands ###
    iter_statements(INSERTS)


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_trainings_gid_usergroups', 'trainings', type_='foreignkey')
    op.drop_constraint('fk_trainings_uid_users', 'trainings', type_='foreignkey')
    op.drop_column('trainings', 'title')
    op.drop_column('trainings', 'sport')
    op.drop_column('trainings', 'rating')
    op.drop_column('trainings', 'heartrate')
    op.drop_column('trainings', 'elevation')
    op.drop_column('trainings', 'duration')
    op.drop_column('trainings', 'distance')
    op.drop_column('trainings', 'description')
    op.drop_column('trainings', 'date')
    ### end Alembic commands ###
    iter_statements(DELETES)
