"""Added strava id

Revision ID: 3b1d44cdad56
Revises: 18cc13347b55
Create Date: 2016-10-21 22:14:59.654682

"""

# revision identifiers, used by Alembic.
revision = '3b1d44cdad56'
down_revision = '18cc13347b55'

from alembic import op
import sqlalchemy as sa


INSERTS = """"""
DELETES = """"""


def iter_statements(stmts):
    for st in [x for x in stmts.split('\n') if x]:
        op.execute(st)


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trainings', sa.Column('strava_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###
    iter_statements(INSERTS)


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trainings', 'strava_id')
    ### end Alembic commands ###
    iter_statements(DELETES)
