"""Added Activity modul

Revision ID: 545a4f2b2e3e
Revises: cab8c02211c6
Create Date: 2016-10-21 15:08:20.763356

"""

# revision identifiers, used by Alembic.
revision = '545a4f2b2e3e'
down_revision = 'cab8c02211c6'

from alembic import op
import sqlalchemy as sa


INSERTS = """
INSERT INTO modules (id, name, description, label, label_plural, clazzpath, display, str_repr, uuid) VALUES (1000, 'activitys', '', 'Activity', 'Activities', 'trainable.model.activity.Activity', 'header-menu', '%s|id', 'aa65cb6d-3d61-43f1-87f1-23e6e00b01c7');
INSERT INTO actions (id, mid, uuid, name, url, icon, bundle, description, display, permission) VALUES (39, 1000, 'cfdb1718-3b3b-43e1-9d54-1681cac5fce4', 'List', 'list', 'icon-list-alt', 'False', '', '', '');
INSERT INTO actions (id, mid, uuid, name, url, icon, bundle, description, display, permission) VALUES (40, 1000, '905beba2-2c1b-4976-9ec5-75fe054c1947', 'Create', 'create', 'icon-plus', 'False', '', '', '');
INSERT INTO actions (id, mid, uuid, name, url, icon, bundle, description, display, permission) VALUES (41, 1000, 'db61f094-26c3-4930-a630-f94cd8eb1cf9', 'Read', 'read/{id}', 'icon-eye-open', 'False', '', '', '');
INSERT INTO actions (id, mid, uuid, name, url, icon, bundle, description, display, permission) VALUES (42, 1000, '9a074f9d-ea32-4dfb-a245-23d1f475595d', 'Update', 'update/{id}', 'icon-edit', 'False', '', '', '');
INSERT INTO actions (id, mid, uuid, name, url, icon, bundle, description, display, permission) VALUES (43, 1000, 'e49028af-a93c-4a20-bc7b-d27ae966e7bc', 'Delete', 'delete/{id}', 'icon-eye-delete', 'False', '', '', '');
INSERT INTO actions (id, mid, uuid, name, url, icon, bundle, description, display, permission) VALUES (44, 1000, '52d7a0ed-959e-489c-96ca-e72ea0166745', 'Import', 'import', 'icon-import', 'False', '', '', '');
INSERT INTO actions (id, mid, uuid, name, url, icon, bundle, description, display, permission) VALUES (45, 1000, '1dd54fbe-808d-47e2-8316-1cbfaefab2c3', 'Export', 'export/{id}', 'icon-export', 'True', '', '', '');
"""
DELETES = """"""


def iter_statements(stmts):
    for st in [x for x in stmts.split('\n') if x]:
        op.execute(st)


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activitys',
    sa.Column('uuid', sa.CHAR(length=36), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('gid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gid'], ['usergroups.id'], name='fk_activitys_gid_usergroups', use_alter=True),
    sa.ForeignKeyConstraint(['uid'], ['users.id'], name='fk_acticitys_uid_users', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    ### end Alembic commands ###
    iter_statements(INSERTS)


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activitys')
    ### end Alembic commands ###
    iter_statements(DELETES)
