"""Added additional fields like weather, wind etc.

Revision ID: 6273e5f2282d
Revises: cbfd33249baa
Create Date: 2016-10-27 21:11:09.612734

"""

# revision identifiers, used by Alembic.
revision = '6273e5f2282d'
down_revision = 'cbfd33249baa'

from alembic import op
import sqlalchemy as sa


INSERTS = """"""
DELETES = """"""


def iter_statements(stmts):
    for st in [x for x in stmts.split('\n') if x]:
        op.execute(st)


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activitys', sa.Column('pain', sa.Integer(), nullable=True))
    op.add_column('activitys', sa.Column('restheartrate', sa.Integer(), nullable=True))
    op.add_column('activitys', sa.Column('sleep', sa.Integer(), nullable=True))
    op.add_column('activitys', sa.Column('temperature', sa.Float(), nullable=True))
    op.add_column('activitys', sa.Column('weather', sa.Integer(), nullable=True))
    op.add_column('activitys', sa.Column('weigth', sa.Float(), nullable=True))
    op.add_column('activitys', sa.Column('wind', sa.Integer(), nullable=True))
    ### end Alembic commands ###
    iter_statements(INSERTS)


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activitys', 'wind')
    op.drop_column('activitys', 'weigth')
    op.drop_column('activitys', 'weather')
    op.drop_column('activitys', 'temperature')
    op.drop_column('activitys', 'sleep')
    op.drop_column('activitys', 'restheartrate')
    op.drop_column('activitys', 'pain')
    ### end Alembic commands ###
    iter_statements(DELETES)
