"""Add athletes role.

Revision ID: 75a3757e6d70
Revises: 166609d1dce1
Create Date: 2016-11-20 14:46:08.630495

"""

# revision identifiers, used by Alembic.
revision = '75a3757e6d70'
down_revision = '166609d1dce1'

from alembic import op
import sqlalchemy as sa


INSERTS = """
INSERT INTO roles (uuid, id, label, name, description, admin, gid, uid) VALUES ('6a6b559b-4e19-4067-aef9-b19fe0bcec4c', 3, 'Athlet', 'athlet', '', false, NULL, 1);
INSERT INTO nm_action_roles (aid, rid) VALUES (41, 3);
INSERT INTO nm_action_roles (aid, rid) VALUES (42, 3);
INSERT INTO nm_action_roles (aid, rid) VALUES (39, 3);
"""
DELETES = """
DELETE FROM nm_action_roles WHERE rid = 3;
DELETE FROM roles WHERE id = 3;
"""


def iter_statements(stmts):
    for st in [x for x in stmts.split('\n') if x]:
        op.execute(st)


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
    iter_statements(INSERTS)


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
    iter_statements(DELETES)
