"""Added category of the trainingplan

Revision ID: b5e3de3611e2
Revises: f1ef05315f2b
Create Date: 2016-12-21 21:59:17.735204

"""

# revision identifiers, used by Alembic.
revision = 'b5e3de3611e2'
down_revision = 'f1ef05315f2b'

from alembic import op
import sqlalchemy as sa


INSERTS = """"""
DELETES = """"""


def iter_statements(stmts):
    for st in [x for x in stmts.split('\n') if x]:
        op.execute(st)


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trainingplans', sa.Column('category', sa.Integer(), nullable=False))
    op.add_column('trainingplans', sa.Column('plan', sa.String()))
    ### end Alembic commands ###
    iter_statements(INSERTS)


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trainingplans', 'category')
    op.drop_column('trainingplans', 'plan')
    ### end Alembic commands ###
    iter_statements(DELETES)
