"""Added commute field to activity.

Revision ID: bf00e371aecb
Revises: 75a3757e6d70
Create Date: 2016-11-22 22:01:09.126475

"""

# revision identifiers, used by Alembic.
revision = 'bf00e371aecb'
down_revision = '75a3757e6d70'

from alembic import op
import sqlalchemy as sa


INSERTS = """"""
DELETES = """"""


def iter_statements(stmts):
    for st in [x for x in stmts.split('\n') if x]:
        op.execute(st)


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activitys', sa.Column('commute', sa.Boolean(), nullable=True))
    ### end Alembic commands ###
    iter_statements(INSERTS)


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activitys', 'commute')
    ### end Alembic commands ###
    iter_statements(DELETES)
