"""Added max_heartrate to profile

Revision ID: c30fe604dac7
Revises: b5e3de3611e2
Create Date: 2017-01-07 21:28:55.206117

"""

# revision identifiers, used by Alembic.
revision = 'c30fe604dac7'
down_revision = 'b5e3de3611e2'

from alembic import op
import sqlalchemy as sa


INSERTS = """"""
DELETES = """"""


def iter_statements(stmts):
    for st in [x for x in stmts.split('\n') if x]:
        op.execute(st)


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('max_heartrate', sa.Integer(), nullable=True))
    ### end Alembic commands ###
    iter_statements(INSERTS)


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'max_heartrate')
    ### end Alembic commands ###
    iter_statements(DELETES)
