"""Added intensity

Revision ID: cbfd33249baa
Revises: e7a82496755d
Create Date: 2016-10-27 11:49:39.957499

"""

# revision identifiers, used by Alembic.
revision = 'cbfd33249baa'
down_revision = 'e7a82496755d'

from alembic import op
import sqlalchemy as sa


INSERTS = """"""
DELETES = """"""


def iter_statements(stmts):
    for st in [x for x in stmts.split('\n') if x]:
        op.execute(st)


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activitys', sa.Column('intensity', sa.Integer(), nullable=True))
    ### end Alembic commands ###
    iter_statements(INSERTS)


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activitys', 'intensity')
    ### end Alembic commands ###
    iter_statements(DELETES)
