"""Added fields for heartrate streams

Revision ID: d05d9ced3e65
Revises: 7e910ab38f9c
Create Date: 2016-11-10 20:43:08.620505

"""

# revision identifiers, used by Alembic.
revision = 'd05d9ced3e65'
down_revision = '7e910ab38f9c'

from alembic import op
import sqlalchemy as sa
import trainable


INSERTS = """"""
DELETES = """"""


def iter_statements(stmts):
    for st in [x for x in stmts.split('\n') if x]:
        op.execute(st)


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activitys', sa.Column('heartrate_stream', trainable.model.activity.Json(), nullable=True))
    ### end Alembic commands ###
    iter_statements(INSERTS)


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activitys', 'heartrate_stream')
    ### end Alembic commands ###
    iter_statements(DELETES)
