"""Added fields to the trainingplan

Revision ID: f1ef05315f2b
Revises: 2bb2f8c5b059
Create Date: 2016-12-01 21:47:27.305422

"""

# revision identifiers, used by Alembic.
revision = 'f1ef05315f2b'
down_revision = '2bb2f8c5b059'

from alembic import op
import sqlalchemy as sa


INSERTS = """
UPDATE modules set str_repr= '%s|name' where id = 1001;
"""
DELETES = """
UPDATE modules set str_repr= '%s|id' where id = 1001;
"""


def iter_statements(stmts):
    for st in [x for x in stmts.split('\n') if x]:
        op.execute(st)


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trainingplans', sa.Column('highlight_1_date', sa.Date(), nullable=True))
    op.add_column('trainingplans', sa.Column('highlight_1_desc', sa.String(), nullable=False))
    op.add_column('trainingplans', sa.Column('highlight_1_title', sa.String(), nullable=False))
    op.add_column('trainingplans', sa.Column('name', sa.String(), nullable=False))
    op.add_column('trainingplans', sa.Column('weekly_hours', sa.Integer(), nullable=False))
    op.create_foreign_key('fk_trainingplans_gid_usergroups', 'trainingplans', 'usergroups', ['gid'], ['id'], use_alter=True)
    op.create_foreign_key('fk_trainingplans_uid_users', 'trainingplans', 'users', ['uid'], ['id'], use_alter=True)
    ### end Alembic commands ###
    iter_statements(INSERTS)


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_trainingplans_uid_users', 'trainingplans', type_='foreignkey')
    op.drop_constraint('fk_trainingplans_gid_usergroups', 'trainingplans', type_='foreignkey')
    op.drop_column('trainingplans', 'weekly_hours')
    op.drop_column('trainingplans', 'name')
    op.drop_column('trainingplans', 'highlight_1_title')
    op.drop_column('trainingplans', 'highlight_1_desc')
    op.drop_column('trainingplans', 'highlight_1_date')
    ### end Alembic commands ###
    iter_statements(DELETES)
